dist: trusty
sudo: false
language: python
matrix:
  include:
  - python: "2.6"
    env: DJVULIBRE=3.5.21 CYTHON=0.19
  - python: "2.7"
    env: DJVULIBRE=3.5.27
  - python: "3.2"
    env: DJVULIBRE=3.5.21 CYTHON=0.20
  - python: "3.3"
    env: DJVULIBRE=3.5.27
  - python: "3.4"
    env: DJVULIBRE=3.5.27
  - python: "3.5"
    env: DJVULIBRE=3.5.27
  - python: "3.6"
    env: DJVULIBRE=3.5.27
  - python: "3.7-dev"
    env: DJVULIBRE=3.5.27
branches:
  except:
  - appveyor
addons:
  apt:
    packages:
    - language-pack-ja
    - ghostscript
cache:
  directories:
  - $HOME/.cache/pip
  - $HOME/.ccache
before_install:
- cython="cython${CYTHON:+==$CYTHON}"
- if [[ $TRAVIS_PYTHON_VERSION = 2.6 ]]; then if_sphinx=:; fi
- if [[ $TRAVIS_PYTHON_VERSION = 3.[23] ]]; then if_sphinx=:; fi
- if [[ $TRAVIS_PYTHON_VERSION = 2.6 ]]; then if_pycodestyle=:; fi
install:
- export PATH="/usr/lib/ccache:$PATH"
- wget https://downloads.sourceforge.net/project/djvu/DjVuLibre/$DJVULIBRE/djvulibre-$DJVULIBRE.tar.gz
- tar -xvvf djvulibre-*.tar.gz
- (cd djvulibre-*/ && ./configure --prefix ~/.local CXXFLAGS="-fpermissive -include cstddef")
- make -C djvulibre-*/libdjvu/ install
- make -C djvulibre-*/tools/ install
- if [[ $DJVULIBRE != 3.5.21 ]]; then make -C djvulibre-*/ install; fi
- export CPATH=~/.local/include/
- export PKG_CONFIG_PATH=~/.local/lib/pkgconfig/
- export LD_LIBRARY_PATH=~/.local/lib/
- pip install --build ~/build-cython $cython
- $if_sphinx pip install sphinx
- $if_pycodestyle pip install pycodestyle
- pip install pydiatra pyflakes
before_script:
- python setup.py build_ext --inplace
script:
- LC_ALL=C nosetests --verbose
- $if_sphinx env PYTHONPATH=$PWD sphinx-build -b doctest doc/api/ tmp
- $if_sphinx private/check-rst
- $if_pycodestyle python -m pycodestyle .
- python -m pydiatra .
- pyflakes .
- python setup.py sdist
- tar -tvf dist/*.tar.gz | { ! grep -F /djvu/config.pxi; }
- python setup.py install
- cd /
- python -c 'import djvu.sexpr, djvu.decode'
- curl -fsS https://pypi.org/simple/djvulibre/; [ $? -eq 22 ]
- curl -fsS https://pypi.org/simple/djvu/; [ $? -eq 22 ]
- curl -fsS https://pypi.org/simple/python-djvu/; [ $? -eq 22 ]

# vim:ts=2 sts=2 sw=2 et
